steps:
  - group: ":lock_with_ink_pen: Security Audits"
    key: "audits"
    steps:
      - label: ":brakeman: Brakeman"
        command: echo "1"
      - label: ":bundleaudit: Bundle Audit"
        command: echo "2"
      - label: ":yarn: Yarn Audit"
        command: echo "3"
      - label: ":yarn: Outdated Check"
        command: echo "4"
